'use client';

import { motion, AnimatePresence } from 'motion/react';
import { Sparkles, AlertCircle, Loader2, RefreshCw, FileText } from 'lucide-react';

import { useStore } from '@/store/useStore';
import { ARTIFACT_LABELS, ARTIFACT_TYPES, type ArtifactPayload, type ArtifactType } from '@/lib/llm/artifactSchemas';
import { cn } from '@/lib/utils';

/**
 * `<ArtifactsPanel />` renders the artifact-generator output: graphic
 * organizers, sentence stems, exit tickets, vocabulary previews, discussion
 * protocols, and single-point rubrics. Each artifact is generated by a
 * dedicated LLM call against `/api/generate-artifacts` AFTER the lesson
 * plan finalizes, so every output is grounded in the actual plan, the
 * chosen text, and the learner profile (not a generic template).
 *
 * The panel renders progressively as SSE events arrive — empty slots show
 * a "generating…" skeleton, completed artifacts pop in. If a single
 * artifact fails (schema mismatch, timeout) we render a small inline
 * fallback instead of poisoning the rest of the panel.
 */

interface ArtifactsPanelProps {
  /** Optional callback to re-trigger generation (e.g. on "Regenerate" click). */
  onRegenerate?: (types?: ArtifactType[]) => void;
}

export function ArtifactsPanel({ onRegenerate }: ArtifactsPanelProps) {
  const artifacts = useStore((s) => s.artifacts);
  const status = useStore((s) => s.artifactStatus);

  const hasAny = Object.keys(artifacts).length > 0;
  const isStreaming = status.kind === 'streaming';

  if (!hasAny && status.kind === 'idle') {
    return null;
  }

  return (
    <section
      aria-label="Generated student artifacts"
      className={cn(
        'rounded-2xl border border-fuchsia-200/70 dark:border-fuchsia-900/40',
        'bg-gradient-to-b from-fuchsia-50/60 to-white dark:from-fuchsia-950/20 dark:to-zinc-950',
        'p-5 sm:p-6 shadow-sm',
      )}
    >
      <header className="flex items-center justify-between gap-3 mb-4">
        <div className="flex items-center gap-2">
          <div className="rounded-lg bg-fuchsia-500/15 p-1.5">
            <Sparkles className="w-4 h-4 text-fuchsia-700 dark:text-fuchsia-300" />
          </div>
          <div>
            <h3 className="text-sm font-semibold text-zinc-900 dark:text-zinc-100">
              Student artifacts
            </h3>
            <p className="text-xs text-zinc-500 dark:text-zinc-400">
              Generated for this lesson, this text, and these learners.
            </p>
          </div>
        </div>
        <div className="flex items-center gap-2">
          <ArtifactStatusBadge />
          {onRegenerate && (
            <button
              type="button"
              onClick={() => onRegenerate()}
              disabled={isStreaming}
              className={cn(
                'inline-flex items-center gap-1.5 rounded-full px-2.5 py-1 text-[11px] font-medium',
                'border border-zinc-200 dark:border-zinc-700',
                'text-zinc-600 dark:text-zinc-300',
                'hover:bg-zinc-50 dark:hover:bg-zinc-800',
                'disabled:opacity-50 disabled:cursor-not-allowed transition-colors',
              )}
            >
              <RefreshCw className={cn('w-3 h-3', isStreaming && 'animate-spin')} />
              {isStreaming ? 'Generating…' : 'Regenerate all'}
            </button>
          )}
        </div>
      </header>

      <div className="grid gap-4 sm:grid-cols-2">
        {ARTIFACT_TYPES.map((type) => {
          const payload = artifacts[type];
          const failure =
            status.kind === 'done' ? status.failed.find((f) => f.type === type) : null;
          return (
            <ArtifactCard
              key={type}
              type={type}
              payload={payload ?? null}
              isStreaming={isStreaming && !payload && !failure}
              failure={failure ? failure.error : null}
              onRegenerate={onRegenerate ? () => onRegenerate([type]) : undefined}
            />
          );
        })}
      </div>

      {status.kind === 'done' && status.failed.length > 0 && (
        <div className="mt-4 rounded-lg border border-amber-200 bg-amber-50 dark:border-amber-900/40 dark:bg-amber-950/20 px-3 py-2">
          <div className="flex items-start gap-2">
            <AlertCircle className="w-4 h-4 mt-0.5 text-amber-700 dark:text-amber-300" />
            <div className="text-xs text-amber-800 dark:text-amber-200">
              {status.failed.length} of {ARTIFACT_TYPES.length} artifacts couldn&apos;t be generated
              this round. The teacher panel still ships with the lesson plan, the chosen text, and
              the artifacts that did succeed.
            </div>
          </div>
        </div>
      )}
    </section>
  );
}

function ArtifactStatusBadge() {
  const status = useStore((s) => s.artifactStatus);

  if (status.kind === 'idle') return null;

  if (status.kind === 'streaming') {
    return (
      <div className="inline-flex items-center gap-1.5 rounded-full bg-fuchsia-500/10 px-2 py-0.5 text-[10px] font-medium text-fuchsia-700 dark:text-fuchsia-300">
        <Loader2 className="w-3 h-3 animate-spin" />
        Streaming
      </div>
    );
  }

  if (status.kind === 'done') {
    return (
      <div className="inline-flex items-center gap-1.5 rounded-full bg-emerald-500/10 px-2 py-0.5 text-[10px] font-medium text-emerald-700 dark:text-emerald-300">
        {status.succeeded.length}/{ARTIFACT_TYPES.length} ready · {(status.latencyMs / 1000).toFixed(1)}s
      </div>
    );
  }

  return (
    <div className="inline-flex items-center gap-1.5 rounded-full bg-rose-500/10 px-2 py-0.5 text-[10px] font-medium text-rose-700 dark:text-rose-300">
      <AlertCircle className="w-3 h-3" />
      Failed
    </div>
  );
}

interface ArtifactCardProps {
  type: ArtifactType;
  payload: ArtifactPayload | null;
  isStreaming: boolean;
  failure: string | null;
  onRegenerate?: () => void;
}

function ArtifactCard({ type, payload, isStreaming, failure, onRegenerate }: ArtifactCardProps) {
  return (
    <article
      className={cn(
        'rounded-xl border bg-white dark:bg-zinc-950 p-4 shadow-sm',
        payload ? 'border-zinc-200 dark:border-zinc-800' : 'border-dashed border-zinc-300 dark:border-zinc-700',
      )}
    >
      <header className="flex items-center justify-between gap-2 mb-3">
        <div className="flex items-center gap-2">
          <FileText className="w-4 h-4 text-zinc-500 dark:text-zinc-400" />
          <h4 className="text-sm font-semibold text-zinc-900 dark:text-zinc-100">
            {ARTIFACT_LABELS[type]}
          </h4>
        </div>
        {onRegenerate && payload && (
          <button
            type="button"
            onClick={onRegenerate}
            className="text-[10px] text-zinc-500 hover:text-zinc-700 dark:hover:text-zinc-300 transition-colors"
          >
            Regenerate
          </button>
        )}
      </header>
      <AnimatePresence mode="wait">
        {failure ? (
          <motion.div
            key="failure"
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            className="text-xs text-rose-700 dark:text-rose-300"
          >
            <div className="flex items-start gap-1.5">
              <AlertCircle className="w-3 h-3 mt-0.5 flex-shrink-0" />
              <div>
                <div className="font-medium">Couldn&apos;t generate this artifact.</div>
                <div className="text-[10px] text-zinc-500 dark:text-zinc-400 mt-0.5">
                  {failure}
                </div>
              </div>
            </div>
          </motion.div>
        ) : payload ? (
          <motion.div
            key={`payload-${type}`}
            initial={{ opacity: 0, y: 4 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.18 }}
          >
            <ArtifactBody payload={payload} />
          </motion.div>
        ) : isStreaming ? (
          <motion.div
            key="streaming"
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            className="space-y-2"
          >
            <div className="h-3 w-3/4 rounded bg-zinc-200/70 dark:bg-zinc-800 animate-pulse" />
            <div className="h-3 w-5/6 rounded bg-zinc-200/70 dark:bg-zinc-800 animate-pulse" />
            <div className="h-3 w-2/3 rounded bg-zinc-200/70 dark:bg-zinc-800 animate-pulse" />
          </motion.div>
        ) : (
          <motion.div
            key="idle"
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            className="text-xs text-zinc-400"
          >
            Will generate after finalize.
          </motion.div>
        )}
      </AnimatePresence>
    </article>
  );
}

/**
 * Render the artifact body. Each type gets a dedicated, print-friendly
 * layout. Because the artifact lane outputs strict-typed JSON, we render
 * structured fields directly instead of free-form markdown.
 */
function ArtifactBody({ payload }: { payload: ArtifactPayload }) {
  switch (payload.type) {
    case 'graphic_organizer':
      return <GraphicOrganizerBody data={payload.data} />;
    case 'sentence_stems':
      return <SentenceStemsBody data={payload.data} />;
    case 'exit_ticket':
      return <ExitTicketBody data={payload.data} />;
    case 'vocabulary_preview':
      return <VocabularyPreviewBody data={payload.data} />;
    case 'discussion_protocol':
      return <DiscussionProtocolBody data={payload.data} />;
    case 'single_point_rubric':
      return <SinglePointRubricBody data={payload.data} />;
  }
}

function SectionTitle({ children }: { children: React.ReactNode }) {
  return (
    <div className="text-sm font-semibold text-zinc-900 dark:text-zinc-100 mb-1.5 leading-snug">
      {children}
    </div>
  );
}

function SectionPurpose({ children }: { children: React.ReactNode }) {
  return (
    <div className="text-xs text-zinc-600 dark:text-zinc-400 mb-3 leading-relaxed">
      {children}
    </div>
  );
}

function MutedLabel({ children }: { children: React.ReactNode }) {
  return (
    <div className="text-[10px] uppercase tracking-wider font-semibold text-zinc-500 dark:text-zinc-400">
      {children}
    </div>
  );
}

function GraphicOrganizerBody({
  data,
}: {
  data: Extract<ArtifactPayload, { type: 'graphic_organizer' }>['data'];
}) {
  return (
    <div className="space-y-3">
      <SectionTitle>{data.title}</SectionTitle>
      <SectionPurpose>{data.purpose}</SectionPurpose>
      <ol className="space-y-2">
        {data.cells.map((cell, idx) => (
          <li
            key={idx}
            className="rounded border border-zinc-200 dark:border-zinc-800 p-2.5 bg-zinc-50/60 dark:bg-zinc-900/40"
          >
            <div className="text-xs font-semibold text-zinc-800 dark:text-zinc-200 mb-1">
              {idx + 1}. {cell.label}
            </div>
            <div className="text-xs text-zinc-700 dark:text-zinc-300 leading-relaxed">
              {cell.prompt}
            </div>
            {cell.sentenceStem && (
              <div className="text-xs italic text-zinc-500 dark:text-zinc-400 mt-1">
                Stem: {cell.sentenceStem}
              </div>
            )}
            {cell.wordBank.length > 0 && (
              <div className="flex flex-wrap gap-1 mt-1.5">
                {cell.wordBank.map((w, i) => (
                  <span
                    key={i}
                    className="rounded bg-fuchsia-100 dark:bg-fuchsia-900/40 px-1.5 py-0.5 text-[10px] text-fuchsia-800 dark:text-fuchsia-200"
                  >
                    {w}
                  </span>
                ))}
              </div>
            )}
          </li>
        ))}
      </ol>
      <div className="rounded bg-amber-50/80 dark:bg-amber-950/20 border border-amber-200/60 dark:border-amber-900/30 p-2 mt-2">
        <MutedLabel>Teacher notes</MutedLabel>
        <div className="text-xs text-amber-900 dark:text-amber-100 mt-0.5 leading-relaxed">
          {data.teacherNotes}
        </div>
      </div>
    </div>
  );
}

function SentenceStemsBody({
  data,
}: {
  data: Extract<ArtifactPayload, { type: 'sentence_stems' }>['data'];
}) {
  return (
    <div className="space-y-3">
      <SectionTitle>{data.title}</SectionTitle>
      <div className="space-y-2">
        {data.rows.map((row, idx) => (
          <div
            key={idx}
            className="rounded border border-zinc-200 dark:border-zinc-800 p-2.5"
          >
            <div className="flex items-center gap-2 mb-1">
              <span className="rounded bg-zinc-100 dark:bg-zinc-800 px-1.5 py-0.5 text-[10px] font-medium text-zinc-700 dark:text-zinc-300">
                {row.audience.replace(/_/g, ' ')}
              </span>
              <span className="text-xs font-semibold text-zinc-800 dark:text-zinc-200">
                {row.function}
              </span>
            </div>
            <ul className="space-y-1">
              {row.stems.map((s, i) => (
                <li
                  key={i}
                  className="text-xs text-zinc-700 dark:text-zinc-300 leading-relaxed"
                >
                  {s}
                </li>
              ))}
            </ul>
          </div>
        ))}
      </div>
      <div className="rounded bg-amber-50/80 dark:bg-amber-950/20 border border-amber-200/60 dark:border-amber-900/30 p-2 mt-1">
        <MutedLabel>Usage</MutedLabel>
        <div className="text-xs text-amber-900 dark:text-amber-100 mt-0.5 leading-relaxed">
          {data.usageNote}
        </div>
      </div>
    </div>
  );
}

function ExitTicketBody({
  data,
}: {
  data: Extract<ArtifactPayload, { type: 'exit_ticket' }>['data'];
}) {
  return (
    <div className="space-y-3">
      <SectionTitle>{data.title}</SectionTitle>
      <div className="text-[10px] text-zinc-500 dark:text-zinc-400">
        Standard: {data.standardCode} · ~{data.timeMinutes} min
      </div>
      <ol className="space-y-2">
        {data.questions.map((q, idx) => (
          <li
            key={idx}
            className="rounded border border-zinc-200 dark:border-zinc-800 p-2.5"
          >
            <div className="flex items-start gap-2">
              <span className="text-xs font-semibold text-zinc-800 dark:text-zinc-200">
                {idx + 1}.
              </span>
              <div className="flex-1">
                <div className="text-xs text-zinc-800 dark:text-zinc-200 leading-relaxed">
                  {q.prompt}
                </div>
                <div className="mt-1 flex items-center gap-2">
                  <span className="rounded bg-zinc-100 dark:bg-zinc-800 px-1.5 py-0.5 text-[10px] text-zinc-600 dark:text-zinc-300">
                    DOK {q.dok}
                  </span>
                </div>
                {q.accommodation && (
                  <div className="text-[10px] italic text-zinc-500 dark:text-zinc-400 mt-1">
                    Accommodation: {q.accommodation}
                  </div>
                )}
                <div className="text-[10px] text-zinc-500 dark:text-zinc-400 mt-1">
                  <span className="font-medium">Expected evidence:</span> {q.expectedEvidence}
                </div>
              </div>
            </div>
          </li>
        ))}
      </ol>
      <div>
        <MutedLabel>Success criteria</MutedLabel>
        <ul className="mt-1 space-y-0.5">
          {data.successCriteria.map((c, i) => (
            <li
              key={i}
              className="text-xs text-zinc-700 dark:text-zinc-300 leading-relaxed"
            >
              · {c}
            </li>
          ))}
        </ul>
      </div>
    </div>
  );
}

function VocabularyPreviewBody({
  data,
}: {
  data: Extract<ArtifactPayload, { type: 'vocabulary_preview' }>['data'];
}) {
  return (
    <div className="space-y-3">
      <SectionTitle>{data.title}</SectionTitle>
      <ul className="space-y-2">
        {data.terms.map((term, idx) => (
          <li
            key={idx}
            className="rounded border border-zinc-200 dark:border-zinc-800 p-2.5"
          >
            <div className="flex items-baseline justify-between gap-2">
              <div className="text-sm font-semibold text-zinc-900 dark:text-zinc-100">
                {term.term}
              </div>
              {term.cognate && (
                <div className="text-[10px] text-zinc-500 dark:text-zinc-400">
                  {term.cognate}
                </div>
              )}
            </div>
            <div className="text-xs text-zinc-700 dark:text-zinc-300 mt-1 leading-relaxed">
              {term.studentDefinition}
            </div>
            <div className="text-[11px] italic text-zinc-600 dark:text-zinc-400 mt-1">
              In text: {term.exampleFromText}
            </div>
            <div className="text-[11px] text-zinc-600 dark:text-zinc-400 mt-1">
              <span className="font-medium">Quick check:</span> {term.quickCheck}
            </div>
          </li>
        ))}
      </ul>
      <div className="rounded bg-amber-50/80 dark:bg-amber-950/20 border border-amber-200/60 dark:border-amber-900/30 p-2 mt-1">
        <MutedLabel>Routine</MutedLabel>
        <div className="text-xs text-amber-900 dark:text-amber-100 mt-0.5 leading-relaxed">
          {data.routine}
        </div>
      </div>
    </div>
  );
}

function DiscussionProtocolBody({
  data,
}: {
  data: Extract<ArtifactPayload, { type: 'discussion_protocol' }>['data'];
}) {
  return (
    <div className="space-y-3">
      <SectionTitle>{data.title}</SectionTitle>
      <div className="text-[10px] text-zinc-500 dark:text-zinc-400">
        {data.structure.replace(/_/g, ' ')} · ~{data.timeMinutes} min
      </div>
      <div className="rounded border border-fuchsia-200/70 dark:border-fuchsia-900/40 bg-fuchsia-50/40 dark:bg-fuchsia-950/20 p-2.5">
        <MutedLabel>Driving question</MutedLabel>
        <div className="text-xs text-fuchsia-900 dark:text-fuchsia-100 mt-0.5 leading-relaxed">
          {data.drivingQuestion}
        </div>
      </div>
      <div className="space-y-2">
        {data.roles.map((role, idx) => (
          <div
            key={idx}
            className="rounded border border-zinc-200 dark:border-zinc-800 p-2.5"
          >
            <div className="text-xs font-semibold text-zinc-800 dark:text-zinc-200">
              {role.name}
            </div>
            <div className="text-xs text-zinc-700 dark:text-zinc-300 mt-1 leading-relaxed">
              {role.responsibility}
            </div>
            <ul className="mt-1.5 space-y-0.5">
              {role.promptStems.map((s, i) => (
                <li
                  key={i}
                  className="text-xs italic text-zinc-600 dark:text-zinc-400 leading-relaxed"
                >
                  · {s}
                </li>
              ))}
            </ul>
          </div>
        ))}
      </div>
      <div>
        <MutedLabel>Accountability</MutedLabel>
        <div className="text-xs text-zinc-700 dark:text-zinc-300 mt-0.5 leading-relaxed">
          {data.accountability}
        </div>
      </div>
      <div>
        <MutedLabel>EL support</MutedLabel>
        <div className="text-xs text-zinc-700 dark:text-zinc-300 mt-0.5 leading-relaxed">
          {data.elSupport}
        </div>
      </div>
    </div>
  );
}

function SinglePointRubricBody({
  data,
}: {
  data: Extract<ArtifactPayload, { type: 'single_point_rubric' }>['data'];
}) {
  return (
    <div className="space-y-3">
      <SectionTitle>{data.title}</SectionTitle>
      <div className="text-[10px] text-zinc-500 dark:text-zinc-400">
        Standard: {data.standardCode}
      </div>
      <div className="text-xs italic text-zinc-700 dark:text-zinc-300 leading-relaxed">
        {data.objective}
      </div>
      <div className="space-y-2">
        {data.criteria.map((c, idx) => (
          <div
            key={idx}
            className="rounded border border-zinc-200 dark:border-zinc-800 p-2.5"
          >
            <div className="text-xs font-semibold text-zinc-800 dark:text-zinc-200">
              {c.criterion}
            </div>
            <div className="grid sm:grid-cols-3 gap-2 mt-1.5 text-xs">
              <div className="rounded bg-emerald-50 dark:bg-emerald-950/20 p-1.5">
                <div className="text-[10px] uppercase tracking-wider text-emerald-700 dark:text-emerald-300 font-semibold">
                  Proficient
                </div>
                <div className="text-emerald-900 dark:text-emerald-100 mt-0.5 leading-relaxed">
                  {c.proficient}
                </div>
              </div>
              <div className="rounded bg-amber-50 dark:bg-amber-950/20 p-1.5">
                <div className="text-[10px] uppercase tracking-wider text-amber-700 dark:text-amber-300 font-semibold">
                  Growth cue
                </div>
                <div className="text-amber-900 dark:text-amber-100 mt-0.5 leading-relaxed">
                  {c.growthCue}
                </div>
              </div>
              <div className="rounded bg-violet-50 dark:bg-violet-950/20 p-1.5">
                <div className="text-[10px] uppercase tracking-wider text-violet-700 dark:text-violet-300 font-semibold">
                  Stretch
                </div>
                <div className="text-violet-900 dark:text-violet-100 mt-0.5 leading-relaxed">
                  {c.extensionCue}
                </div>
              </div>
            </div>
          </div>
        ))}
      </div>
      <div>
        <MutedLabel>Student self-check</MutedLabel>
        <ul className="mt-1 space-y-0.5">
          {data.studentSelfCheck.map((c, i) => (
            <li
              key={i}
              className="text-xs text-zinc-700 dark:text-zinc-300 leading-relaxed"
            >
              · {c}
            </li>
          ))}
        </ul>
      </div>
    </div>
  );
}
